version: '3.7'

services:

  react-nginx:
    build:
      context: ./react
      dockerfile: Dockerfile
    environment:
      - LETSENCRYPT_HOST=hnefatafl.fastiz.dev
      - VIRTUAL_HOST=hnefatafl.fastiz.dev
    expose:
      - "80"
    network_mode: jwilder-nginx-proxy_proxy
  express:
    build:
      context: ./express
      dockerfile: Dockerfile
    environment:
      - LETSENCRYPT_HOST=api.hnefatafl.fastiz.dev
      - VIRTUAL_HOST=api.hnefatafl.fastiz.dev
      expose:
        - "8080"
      network_mode: jwilder-nginx-proxy_proxy
