version: '3.7'

services:

  react-nginx:
    build:
      context: ./react
      dockerfile: Dockerfile
    environment:
      - LETSENCRYPT_HOST=fastiz.dev
      - VIRTUAL_HOST=fastiz.dev
    expose:
      - 80
  express:
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
    - '8080:8080'